
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ve.edu.unet;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 33;
  public static final int OVER = 22;
  public static final int GE = 28;
  public static final int SEMI = 39;
  public static final int LPAREN = 37;
  public static final int REPEAT = 6;
  public static final int INT = 10;
  public static final int FOR = 8;
  public static final int MINUS = 20;
  public static final int WRITE = 13;
  public static final int RPAREN = 38;
  public static final int NOT = 32;
  public static final int AND = 30;
  public static final int LT = 25;
  public static final int OR = 31;
  public static final int UNTIL = 7;
  public static final int NUM = 36;
  public static final int PLUS = 19;
  public static final int ASSIGN = 17;
  public static final int IF = 2;
  public static final int ID = 35;
  public static final int LE = 26;
  public static final int EOF = 0;
  public static final int BOOLEAN = 9;
  public static final int RBRACKET = 34;
  public static final int TRUE = 15;
  public static final int error = 1;
  public static final int MOD = 23;
  public static final int EQ = 24;
  public static final int VECTOR = 11;
  public static final int TIMES = 21;
  public static final int ELSE = 4;
  public static final int READ = 12;
  public static final int TO = 18;
  public static final int THEN = 3;
  public static final int NE = 29;
  public static final int END = 5;
  public static final int FALSE = 16;
  public static final int GT = 27;
  public static final int DO = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "THEN",
  "ELSE",
  "END",
  "REPEAT",
  "UNTIL",
  "FOR",
  "BOOLEAN",
  "INT",
  "VECTOR",
  "READ",
  "WRITE",
  "DO",
  "TRUE",
  "FALSE",
  "ASSIGN",
  "TO",
  "PLUS",
  "MINUS",
  "TIMES",
  "OVER",
  "MOD",
  "EQ",
  "LT",
  "LE",
  "GT",
  "GE",
  "NE",
  "AND",
  "OR",
  "NOT",
  "LBRACKET",
  "RBRACKET",
  "ID",
  "NUM",
  "LPAREN",
  "RPAREN",
  "SEMI"
  };
}

